"""Copy the overlay into the pinned VideoLingo checkout and patch it.

Order matters. Overlay files that shadow an upstream module are copied *after*
the original is preserved under a `_upstream` name, because two of our modules
import upstream logic they deliberately reuse (`_8_2_dub_chunks` keeps
upstream's timing analysis and replaces only the fragile string matching).
"""

from __future__ import annotations

import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from asmrdub import patches, pins, vl_config

BOLD = "\033[1m"
RESET = "\033[0m"


def say(message: str) -> None:
    print(f"{BOLD}[overlay]{RESET} {message}", flush=True)


# Upstream modules we must keep a copy of because an overlay file imports them.
PRESERVE = (
    ("core/_8_2_dub_chunks.py", "core/_8_2_dub_chunks_upstream.py"),
)


def preserve_upstream(repo_root: str) -> None:
    for original, kept in PRESERVE:
        source = os.path.join(repo_root, original)
        target = os.path.join(repo_root, kept)
        if not os.path.isfile(source):
            raise RuntimeError(f"cannot preserve missing upstream file: {original}")
        if os.path.isfile(target):
            continue
        shutil.copy2(source, target)
        say(f"preserved {original} -> {kept}")


def copy_overlay(overlay_root: str, repo_root: str) -> list[str]:
    """Copy every file under ``overlay_root`` into ``repo_root``."""
    copied = []
    for current, _, files in os.walk(overlay_root):
        if "__pycache__" in current:
            continue
        for name in files:
            if name.endswith(".pyc"):
                continue
            source = os.path.join(current, name)
            relative = os.path.relpath(source, overlay_root)
            target = os.path.join(repo_root, relative)
            os.makedirs(os.path.dirname(target), exist_ok=True)
            shutil.copy2(source, target)
            copied.append(relative.replace(os.sep, "/"))
    for relative in sorted(copied):
        say(f"copied {relative}")
    return copied


def write_requirements(repo_root: str) -> str:
    """Emit a torch-free requirements file for the app environment.

    Upstream's list drags in whisperX (torch~=2.8 + torchvision + torchcodec)
    and pyannote. Those belong to the GPU worker's environment; installing them
    here would either fight IndexTTS's pins or silently downgrade numpy under
    Kaggle's preinstalled stack.
    """
    source = os.path.join(repo_root, "requirements.txt")
    with open(source, "r", encoding="utf-8") as fh:
        kept = patches.filter_requirements(fh.readlines())
    kept.extend(patches.APP_EXTRA_REQUIREMENTS)
    target = os.path.join(repo_root, "requirements-app.txt")
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(
            "# generated by asmr-dub: upstream requirements minus torch pullers\n"
        )
        fh.write("\n".join(kept) + "\n")
    say(f"wrote {os.path.basename(target)} ({len(kept)} packages)")
    return target


def apply_config(repo_root: str, ollama_model: str, llm_base_url: str) -> None:
    """Merge our overrides into VideoLingo's config.yaml via its own writer.

    Using `update_key` rather than editing the YAML keeps comments intact and
    fails loudly on a key that no longer exists -- which is the signal that the
    upstream pin moved.
    """
    sys.path.insert(0, repo_root)
    previous = os.getcwd()
    os.chdir(repo_root)   # config_utils resolves 'config.yaml' relatively
    try:
        from core.utils.config_utils import update_key

        overrides = vl_config.config_overrides(
            ollama_model=ollama_model, llm_base_url=llm_base_url
        )
        for key, value in vl_config.flatten(overrides):
            update_key(key, value)
            say(f"config {key} = {value!r}")
    finally:
        os.chdir(previous)


def ensure_custom_terms(repo_root: str) -> None:
    """`_4_1_summarize` reads custom_terms.xlsx unconditionally.

    Upstream ships one, but a shallow clone or a stray .gitignore has been
    enough to lose it before; an empty three-column sheet satisfies the reader.
    """
    path = os.path.join(repo_root, "custom_terms.xlsx")
    if os.path.isfile(path):
        return
    import pandas as pd

    pd.DataFrame(columns=["src", "tgt", "note"]).to_excel(path, index=False)
    say("created empty custom_terms.xlsx")


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--overlay-root", required=True)
    parser.add_argument("--ollama-model", default=pins.OLLAMA_MODEL)
    parser.add_argument(
        "--llm-base-url", default=f"http://127.0.0.1:{pins.OLLAMA_PORT}/v1"
    )
    parser.add_argument("--skip-config", action="store_true")
    args = parser.parse_args()

    repo_root = os.path.abspath(args.repo_root)
    overlay_root = os.path.abspath(args.overlay_root)

    preserve_upstream(repo_root)
    applied = patches.apply_patches(repo_root)
    for line in applied:
        say(f"patched {line}")
    copy_overlay(overlay_root, repo_root)
    write_requirements(repo_root)
    if not args.skip_config:
        ensure_custom_terms(repo_root)
        apply_config(repo_root, args.ollama_model, args.llm_base_url)
    say("overlay applied")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
